name: Julia CI
on: push
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup
      uses: julia-actions/setup-julia@latest
      with:
        version: 1.3.1
    - name: Run test
      run: julia main.jl
